sudo: required

services:
  - docker

before_install:
  - docker build -t cizuss/mc-aws-playground-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run cizuss/mc-aws-playground-client-test npm run test -- --coverage

after_success:
  - docker build -t cizuss/mc-aws-playground-client ./client
  - docker build -t cizuss/mc-aws-playground-nginx ./nginx
  - docker build -t cizuss/mc-aws-playground-server ./server
  - docker build -t cizuss/mc-aws-playground-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push cizuss/mc-aws-playground-client
  - docker push cizuss/mc-aws-playground-nginx
  - docker push cizuss/mc-aws-playground-server
  - docker push cizuss/mc-aws-playground-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "mc-aws-playground"
  env: "AwsPlayground-env"
  bucket_name: "elasticbeanstalk-us-east-2-668099751442"
  bucker_path: "mc-aws-playground"
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"